# Generated by Django 5.2.7 on 2025-10-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estante', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estante',
        ),
    ]
