# Generated by Django 5.2.7 on 2025-11-26 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('descripcion', models.TextField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
            },
        ),
        migrations.CreateModel(
            name='Archivador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'verbose_name': 'Archivador',
                'verbose_name_plural': 'Archivadores',
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, max_length=5000, null=True)),
                ('archivo', models.FileField(upload_to='archivos/')),
                ('archivador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='ambiente.archivador')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=5000, null=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estantes', to='ambiente.ambiente')),
            ],
            options={
                'verbose_name': 'Estante',
                'verbose_name_plural': 'Estantes',
            },
        ),
        migrations.AddField(
            model_name='archivador',
            name='estante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivadores', to='ambiente.estante'),
        ),
    ]
