# Generated by Django 5.2.7 on 2025-10-24 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente',
            name='ubicacion',
        ),
    ]
