# Generated by Django 5.2.7 on 2025-11-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('users', 'modulo de usuarios'), ('ambiente', 'modulo de sistema de archivos'), ('archivo', 'modulo de vista de archivos')],
            },
        ),
    ]
